name: cache-test-data
description: Share test result data between run attempts

runs:
  using: composite
  steps:
    - name: Generate Restore Keys
      id: generate-restore-keys
      shell: bash
      run: |
        echo "primary-key=d2l-test-${{ github.run_id }}-${{ github.run_attempt }}" > ${GITHUB_OUTPUT}
        echo "previous-attempt-key=d2l-test-${{ github.run_id }}-$((${{ github.run_attempt }} - 1))" >> ${GITHUB_OUTPUT}
    - name: Cache Test Data
      uses: bearfriend/cache@save-always-output
      id: d2l-test-data
      with:
        path: .d2l-test
        save-always: true
        key: ${{ steps.generate-restore-keys.outputs.primary-key }}
        restore-keys: ${{ steps.generate-restore-keys.outputs.previous-attempt-key }}
